# Generated by Django 3.1.3 on 2022-06-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('razas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raza',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
